### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by alexrosenfeld10** [xplicit/ansible-net#7]
Looks like there are some recent commits, but no new releases. Wondering if it's maintained still

**Comment by xplicit** [comment]
I did not see that anyone used .net to ansible bridge that's why the project is not updated on nuget. If you think that the latest commits are useful for your needs I can redeploy package to nuget with the latest changes.

**Comment by alexrosenfeld10** [comment]
Thanks. I appreciate it. I am working on a command line tool for a baseline library that handles lots of basics at my company, and I'm considering using this package. I am yet to really test things out end to end, but as of now this looks to be helpful! Thank you.

**Comment by xplicit** [comment]
The latest changes were published. Version 1.0.3 is available on NuGet.
